name: Production Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, macrotech-actions-runner]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Buildx
      run: |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap

    - name: Build Docker Image
      run: |
        docker buildx build \
          -f docker/php/Dockerfile \
          -t codeigniter-frontend:latest \
          --load .

    - name: Deploy Stack
      run: |
        cd /var/www/collection-frontend
        docker-compose down
        docker-compose up -d --build
        docker exec app chmod -R 755 writable
        docker exec app chown -R www-data:www-data writable
